### ISSUE TITLE
SQLJ Java8 support

### ISSUE THREAD

**Issue by avialias** [mojohaus/sqlj-maven-plugin#3]
Please can you do support for Java8.

Sqlj-maven-plugin does not work when maven is run with Java8, and I cant use Java7 anymore.

I think the problem is in java.io package because its note anymore in Java8, so it should use nio package.

Please respond, with you opinion.

**Comment by andham** [comment]
You will need to provide more details. Personally I'm not using sqlj any more so the fastest way forward is for you to provide a PR with a fix.

**Comment by avialias** [comment]
Ok , this is error on Maven scripe running sqlj:sqlj, Maven started with Oracle jdk 1.8.0_60 x64

Please write me your opinion on error

2018-03-02 12:06:32.253 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
2018-03-02 12:06:32.253 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - BUILD FAILURE
2018-03-02 12:06:32.253 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
2018-03-02 12:06:32.253 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - Total time: 1.216 s
2018-03-02 12:06:32.253 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - Finished at: 2018-03-02T12:06:32+01:00
2018-03-02 12:06:32.331 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - Final Memory: 8M/193M
2018-03-02 12:06:32.331 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
2018-03-02 12:06:32.331 [main] [ERROR] org.apache.maven.cli.MavenCli - Failed to execute goal org.codehaus.mojo:sqlj-maven-plugin:1.3:sqlj (default-cli) on project bss-batch-java: null: MojoFailureException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:sqlj-maven-plugin:1.3:sqlj (default-cli) on project bss-batch-java: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException
	at org.codehaus.mojo.sqlj.SqljMojo.translate(SqljMojo.java:301)
	at org.codehaus.mojo.sqlj.SqljMojo.execute(SqljMojo.java:136)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more

**Comment by andham** [comment]
This problem could be pretty much anything. Maybe some misconfiguration?
You should provide a test project demonstrating the issue. However, not many people use sqlj today so if this is urgent for you I would recommend that you grab the source code, trouble shoot, and provide a PR with a fix.

**Comment by avialias** [comment]
I debuged sqlj-maven-plugin v 1.3 and its not problem in there. Problem is in sqlj.jar provided by db provider.

Its reported on 
http://www-01.ibm.com/support/docview.wss?uid=swg1IT12454


Thx...

**Comment by andham** [comment]
Yes, I've run into similar Java 8 problem with DB2 driver earlier. Maybe the same problem. It was fixed in a newer version of the driver.
I'm closing this issue. Good debug job ruling out the plugin. :-)
